server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10011/eureka

spring:
  application:
    name: gateway-service

zuul:
  routes:
    consumer-service: /**
  ignored-services:
    - user-service

#hystrix熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

#ribbon 负载均衡
ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 2000
  MaxAutoRetriesNextServer: 0 #不重试