server:
  port: 8888

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///usermanager
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10011/eureka,http://127.0.0.1:10012/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

mybatis:
  type-aliases-package: cn.edu.hhuwtian.pojo
